### ISSUE TITLE
[Bug]: Add user-specified volumes to chart template

### ISSUE THREAD

**Issue by theobjectivedad** [memgraph/helm-charts#20]
### Contact Details

theobjectivedad@gmail.com

### What happened?

This feature would allow users to add additional volume mounts to memgraph from either config maps or secrets. There are many use cases where this is useful including making cluster-managed certificates and trust chains available to memgraph and memgraph-lab.

ex, memgraph support for cluster managed TLS certs for bolt:

```shell
...
--bolt-cert-file=/run/secrets/tls/tls.crt"
--bolt-key-file=/run/secrets/tls/tls.key"
```

and (memgraph-lab), needed to trust local ollama / other services that use certs managed by a private CA:

```shell
NODE_EXTRA_CA_CERTS=/run/app/trust/trust.pem
```

### Chart type

Standalone

### Chart version

0.1.1

### Environment

Local Machine

### Relevant log output

```shell
N/A
```

**Comment by antejavor** [comment]
Hi @theobjectivedad, thanks for opening this issue 🙇‍♂️ , we will try to integrated this in upcoming release cycle. Stay tuned for more.
