### ISSUE TITLE
[Bug]: Issue with cluster setup test and checking the health instances 

### ISSUE THREAD

**Issue by antejavor** [memgraph/helm-charts#21]
### What happened?

Health: ["up"]
Non-up health found: ["up"]
Health: ["up"]
Non-up health found: ["up"]
Health: ["up"]
Non-up health found: ["up"]
Health: ["up"]
Non-up health found: ["up"]
Health: ["up"]
Non-up health found: ["up"]
Instance count: 5
Health OK: 0
Check failed. Either not all instances are up or the count is not 5.

### Chart type

Standalone

### Chart version

0.1.0

### Environment

Local Machine

### Relevant log output

```shell
Health: ["up"]
Non-up health found: ["up"]
Health: ["up"]
Non-up health found: ["up"]
Health: ["up"]
Non-up health found: ["up"]
Health: ["up"]
Non-up health found: ["up"]
Health: ["up"]
Non-up health found: ["up"]
Instance count: 5
Health OK: 0
Check failed. Either not all instances are up or the count is not 5.
```

**Comment by antejavor** [comment]
Maybe generic chart testing action can be configured: https://github.com/helm/chart-testing/blob/main/doc/ct_install.md#options

**Comment by antejavor** [comment]
Also, I updated the test names to match each chart.

**Comment by antejavor** [comment]
@as51340 we can probably close this one?

**Comment by as51340** [comment]
We can close this @antejavor yes.
