### ISSUE TITLE
[Feature]: Allow memgraph to accept tolerations and nodeSelectors

### ISSUE THREAD

**Issue by sentientmonkey** [memgraph/helm-charts#40]
👋 I have a small PR open [here](https://github.com/memgraph/helm-charts/pull/39) to allow the memgraph chart to accept tolerations and node selectors. It's backwards-compatible and follows the same patterns as the memgraph-labs chart.

I've tested locally with `helm template` & verified on a GKE cluster that these work correctly.

**Comment by antejavor** [comment]
This has been added here: https://github.com/memgraph/helm-charts/pull/39

**Comment by sentientmonkey** [comment]
@antejavor thank you!
