### ISSUE TITLE
[Bug]: Allow setting username and password via kubernetes secrets

### ISSUE THREAD

**Issue by alex-linx** [memgraph/helm-charts#5]
### What happened?

It's not really bug, but a suggestion for the chart.
When the chart is installed for the first time it has no username and password so you can just log in.
It would be nice to have an optional values setting for setting the username and password.

Ideally it would be possible to set them using both env vars and MEMGRAPH_PASSFILE (which I think is a bit more secure).

Maybe something like this (in `values.yaml`)
```
secret:
	secretName: memgraph-secret
	usernKey: MEMGRAPH_USER
	passwordKey: MEMGRAPH_PASSWORD
	passfileKey: MEMGRAPH_PASSKEY
```
If secretName is defined then:
- If passFileKey is provided - its contents are mounted somewhere into the pod (say `/secrets/MEMGRAPH_PASSFILE`) and the env var MEMGRAPH_PASSFILE is set to that path.
- Otherwise the usernameKey and passwordKey secret values are mounted into the `MEMGRAPH_USER` and `MEMGRAPH_PASSWORD` env vars respectively.

### Chart type

Standalone

### Chart version

0.1.0

### Environment

Amazon Web Services

**Comment by antejavor** [comment]
Hi @alex-linx, thanks for providing this feedback 🙌, we will probably add this in following weeks.

**Comment by aqeelat** [comment]
Hi @antejavor, any updates?

**Comment by aqeelat** [comment]
I can open a PR for the change (excluding passfileKey)

**Comment by antejavor** [comment]
Hi @aqeelat, thanks for reaching out 🚀 , I will fix it in the upcoming release.  If you have a template ready feel free to open a PR so we will include it.
