### ISSUE TITLE
[Bug]: Pod not created in OpenShift cluster when running helm install

### ISSUE THREAD

**Issue by DavIvek** [memgraph/helm-charts#50]
### What happened?

After setting up OpenShift cluster (locally with `crc`, Ubuntu 22.04) and running helm install, pod is not created.
![Screenshot from 2024-07-26 15-37-21](https://github.com/user-attachments/assets/6fed1c52-1a15-4d11-8fc5-3a655460fbf4)

### Chart type

Standalone

### Chart version

0.1.0

### Environment

Local Machine

**Comment by as51340** [comment]
Closing it, not issue anymore
