### ISSUE TITLE
Injecting custom query modules

### ISSUE THREAD

**Issue by matkob** [memgraph/helm-charts#66]
Hi, as the title suggests, I'd like to add the capability to mount custom query modules into the app during the deployment. I know one way would be to bake these files into the Docker image but I'd prefer to keep them separate to avoid having to maintain one extra component.

Would you be interested in a small contribution? I have the code almost ready :)

**Comment by katarinasupe** [comment]
Hi @matkob, of course, we would be interested in such a contribution. I would love to see your approach 😄

**Comment by matkob** [comment]
Hey, good to hear :) I've submitted the PR but didn't include much in the description. Let me know what's the way to go about the PRs - if I should document the work there or a link to this issue is enough.

**Comment by katarinasupe** [comment]
Having an issue describing what you did linked is good enough. Thank you 🙏
