### ISSUE TITLE
Memgraph container mounts lib-storage volume on /var/log/memgraph

### ISSUE THREAD

**Issue by stymp** [memgraph/helm-charts#69]
In memgraph chart, lib-storage volume is mounted twice by the memgraph container, under /var/lib/memgraph and /var/log/memgraph. I suspect line 182 on the statefulset definition template should read 

` - name: {{ include "memgraph.fullname" . }}-log-storage` 

instead of 

` - name: {{ include "memgraph.fullname" . }}-lib-storage`

See https://github.com/memgraph/helm-charts/blob/main/charts/memgraph/templates/statefulset.yaml for definition template.

**Comment by antejavor** [comment]
Hi @stymp, thanks for reporting this it will be fixed 🦾
