### ISSUE TITLE
Add config for vm.max_map_count to helm charts. 

### ISSUE THREAD

**Issue by antejavor** [memgraph/helm-charts#74]
If the config is too low by default, during high load procedures, this will happen: 

`Max virtual memory areas vm.max_map_count 65530 is too low, increase to at least 262144 `

We should set a bigger default and enable users to change this.

**Comment by gitbuda** [comment]
Quick note/question: is it true that the settings have to be done on the host machine/OS -> what's the best way to do that when k8s is used?

**Comment by antejavor** [comment]
@gitbuda Yes, or you need to use the privilege mode in docker/k8s.
